### ISSUE TITLE
Android Studio 2020.3.1 incompatibility

### ISSUE THREAD

**Issue by Arnaudv6** [bmikaili/intellij-monocai-theme#19]
Hello and thanks for this awesome theme. I have been using it daily for work since 4 months now,
and this improves my mood with happier colors over default dark theme (darkula).
(I am using it for editor only, not full IDE, as it does not cover every readability cases)

I just updated android studio to version 2020.3.1 and... the theme can't be applied anymore (module installed, but theme not listed).

Any chance you still support this theme?
Thanks

**Comment by nikunjparadva** [comment]
## Here is the Solution
https://stackoverflow.com/a/68599712/5773037

**Comment by Arnaudv6** [comment]
OK ! sorry for invalid issue so, and thanks for your support !
