### ISSUE TITLE
The active selected Tab in Terminal section, or in Version Control Section is Unreadable

### ISSUE THREAD

**Issue by dolpsdw** [bmikaili/intellij-monocai-theme#2]
The active selected Tab in Terminal section, or in Version Control Section is Unreadable

**Comment by bmikaili** [comment]
I looked into this, but as the official documentation for Editor themes by Jetbrains is very scarce, I can't find the appropriate key to change that color.

If anyone else has input, that would be cool.

**Comment by bmikaili** [comment]
Is fixed in version 1.4. Appropriate key was "Tool Window".
