### ISSUE TITLE
Smart casts in Kotlin colored too brightly

### ISSUE THREAD

**Issue by Sroka** [bmikaili/intellij-monocai-theme#3]
Hell, thank you for this awesome plugin, I ended up using it in all Jetbrains IDEs :) 

It works flawlessly with every language I tried it with, I only have one minor issue with Kotlin and Smartcasts. By default they have a #DBFFDB backgroud which makes them unreadable:
![image](https://user-images.githubusercontent.com/2983710/56139145-96222a80-5f98-11e9-80cc-903222e8f8b8.png)

I can submit a PR, for this but I would like to know which color do you think would suit this use case the best?

**Comment by bmikaili** [comment]
Hey, thanks for the feedback!

What color do they use in Darcula? Then we could use a similar color for this plugin.

**Comment by Sroka** [comment]
Hmm, it seems that #223C23 :
![image](https://user-images.githubusercontent.com/2983710/56159562-50c82200-5fc5-11e9-9fa1-069821eaed16.png)

But now we mention it I'm not sure I like it :P

**Comment by bmikaili** [comment]
Alright, I added a dark green color. You will be able to see the changes in version 1.4.
