### ISSUE TITLE
Future work and improvements

### ISSUE THREAD

**Issue by up-to-you** [bmikaili/intellij-monocai-theme#6]
Hey, do you plan to continue evolve your awesome theme ?
Take a look at exponential growth in "top voted" and "most installed" themes:
https://plugins.jetbrains.com/contest/intellij-themes/2019

Just trying to clarify - will you work at this project or is it abandoned ?

**Comment by bmikaili** [comment]
Hey,

I wouldn't call it abandoned, no. Are there any changes in particular you would be interested in?
