### ISSUE TITLE
The hook in the checkbox is not well recognizable

### ISSUE THREAD

**Issue by sabf81** [bmikaili/intellij-monocai-theme#7]
The checked checkboxes are currently difficult to identify. A slightly lighter color should be selected here.
<img width="1473" alt="monocaiCheckbox" src="https://user-images.githubusercontent.com/13674691/65938649-cd3fa780-e423-11e9-8c48-cb8bc01c19ec.png">

**Comment by lipemorais** [comment]
I would like to help with this and other features but I'm not able to setup the project. @bmikaili can you help me with it?

**Comment by bmikaili** [comment]
Of course! This article is a good start: http://www.jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes.html

Basically just open the project in IntellIJ, Resources/Monocai.theme.json is the file where everything is configured. There you can set colors with the different keys.

To build and test, look at this: http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/running_and_debugging_a_plugin.html

**Comment by lipemorais** [comment]
I have tried to check why this issue is back but I was not able to find why. Looks that the #5 should be still working but it is not.

**Comment by bmikaili** [comment]
I looked at it as well. All the checkbox keys have the correct colors, so I'm not sure why this occurs.

**Comment by sabf81** [comment]
maybe it is because of the dark theme of mac os?

**Comment by lipemorais** [comment]
The theme for mac os does not influence it. It's somehow configuration inside IntelliJ

**Comment by sabf81** [comment]
After an update the hooks are better visible!
<img width="1684" alt="hookIntelliJ" src="https://user-images.githubusercontent.com/13674691/67657189-59c38400-f956-11e9-97d4-b049f35a92e2.png">

**Comment by bmikaili** [comment]
Thanks so much for contributing!

**Comment by bmikaili** [comment]
Weird. Wonder what it was.
