### ISSUE TITLE
The bar with the hint to install a PlugIn is bad readable

### ISSUE THREAD

**Issue by sabf81** [bmikaili/intellij-monocai-theme#9]
The text color in the bar to install a PlugIn is to bright see screenshot 
<img width="1795" alt="IntelliJIntallHintNotReadable" src="https://user-images.githubusercontent.com/13674691/68028439-2e71c980-fcb5-11e9-9ac6-f80719542e2c.png">

**Comment by bmikaili** [comment]
I think this is related to https://github.com/bmikaili/intellij-monocai-theme/issues/4.

I still don't know which key is used to configure that part of the IDE.
